#This file was generated by Google's AI - Gemini
# ImportFont.py
import os
import customtkinter as ctk
from customtkinter import CTkFont

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

font_file_path = os.path.join(SCRIPT_DIR, "Fonts", "KaiseiHarunoUmi-Regular.ttf")

# Check and register the font dynamically with the OS backend
if os.path.exists(font_file_path):
    ctk.FontManager.load_font(font_file_path)
    FONT_AVAILABLE = True
else:
    print(f"Error: Could not find '{font_file_path}'. Using system fallbacks.")
    FONT_AVAILABLE = False
