#Saving & loading the data --- This file is generated by GPT :/ *sorry*

import os

NOTES_FILE = "Notes.txt"
NAMES_FILE = "Note_Names.txt"

NOTE_START = "!-----<<<NOTE_START>>>-----!"
NOTE_END = "!-----<<<NOTE_END>>>-----!"


def load_notes():
    Notes = []
    Note_Names = []

    # Create files if they don't exist
    if not os.path.exists(NOTES_FILE):
        open(NOTES_FILE, "w", encoding="utf-8").close()

    if not os.path.exists(NAMES_FILE):
        open(NAMES_FILE, "w", encoding="utf-8").close()

    # -------------------------
    # Load note names
    # -------------------------

    with open(NAMES_FILE, "r", encoding="utf-8") as file:
        Note_Names = [
            line.rstrip("\n")
            for line in file
        ]

    # -------------------------
    # Load notes
    # -------------------------

    with open(NOTES_FILE, "r", encoding="utf-8") as file:
        content = file.read()

    if content.strip():
        sections = content.split(NOTE_START)

        for section in sections:
            section = section.strip()

            if not section:
                continue

            if NOTE_END in section:
                note = section.split(NOTE_END, 1)[0]
                Notes.append(note.strip("\n"))

    # -------------------------
    # Make lists match
    # -------------------------

    while len(Notes) < len(Note_Names):
        Notes.append("")

    while len(Note_Names) < len(Notes):
        Note_Names.append(f"Note {len(Note_Names) + 1}")

    return Notes, Note_Names

def save_notes(Notes, Note_Names):
